### ISSUE TITLE
How do I align Float Action Button 

### ISSUE THREAD

**Issue by WaqarSarfaraz** [aimore/XamUI#3]
I just Download your project but float action button is render on left side of the screen.. I want to show the float button on the center of the screen...
Thanks in Advance

**Comment by aimore** [comment]
Can you give me more details?
Android or iOS?

**Comment by WaqarSarfaraz** [comment]
I want to move the float action button.. ihave changed the margin & Padding but nothing happen below are margin code onElementChanged() Method
marginLayout.SetMargins((int)(width / 2.3), 0, 0, 40);

**Comment by aimore** [comment]
If you want to align the items on the BottomBar you will need to change the following values:

FAB:
 marginLayout.SetMargins((int)(width / 2.3), 0, 0, 40);
https://github.com/aimore/XamUI/blob/52d1fcbfae980f7ee9951bce35f0abdee5025a58/XamFood/XamFood.Android/Renderers/CustomBottomBarRenderer.cs#L44

ICONS:
   item2.SetPadding(0, 0, 100, 0);
  item3.SetPadding(100,0,0,0);

**Comment by WaqarSarfaraz** [comment]
Thanks it's work
