### ISSUE TITLE
How i can use/call fab/center tab option from shared code.

### ISSUE THREAD

**Issue by DevXtranet** [aimore/XamUI#4]
In the current implementation, you are showing toast and alert message from native projects but I want to access the fab button from shared project folder/code.

**Comment by aimore** [comment]
You can create a new Bindable property passing an Action
ref: https://stackoverflow.com/questions/37997926/passing-event-to-xaml-object-using-binding
or use Xamarin forms MessagingCenter to subscribe events 
ref: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center
