### ISSUE TITLE
Does not render the "Plus" button on iOS 13.2

### ISSUE THREAD

**Issue by Syed-Esqimo** [aimore/XamUI#6]
![image](https://user-images.githubusercontent.com/51115792/68399210-f9122380-016d-11ea-872e-a65432007df4.png)

**Comment by aimore** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-08 at 10 49 56](https://user-images.githubusercontent.com/8807639/68437627-9d9b7080-0215-11ea-9e2c-22f1e1339bf7.png)
<img width="446" alt="Screen Shot 2019-11-08 at 10 50 19 am" src="https://user-images.githubusercontent.com/8807639/68437628-9d9b7080-0215-11ea-8d4f-b62670b0d81d.png">

I have tested on the following simulator - iPhone 11 pro Max iOS 13.1 and could not reproduce the missing plus button in the BottomBar 

Could you tell me the device/simualtor you are testing?
